### ISSUE TITLE
This repository infringes a copyright of Marceau Maubert ( @Tenrys )

### ISSUE THREAD

**Issue by Collision02** [7Flixs/glua_discord#1]
Hi!

I'm authorized to act on Marceau's behalf.
It seems that you have used his [code](https://github.com/Tenrys/gmod_discordrpc/blob/master/LICENSE)  without accrediting him, and you have also changed the license of his code.
See: [his code](https://github.com/Tenrys/gmod_discordrpc/blob/master/lua/discordrpc/init.lua#L34), [code in this repo](https://github.com/7Flixs/glua_discord/blob/4daf103b57138d958891d646fb0faef3fc84e46e/discord/cl_discord.lua#L101).
His code is licensed under GNU GPL 3.0 which does not give you the right to re-license it.

Please modify the repository according to these lawful demands.

**Comment by 7Flixs** [comment]
Hey, I'm sorry to hear that you think that. I took the advice and pushed an changed port validator, that should fit your needs!

**Comment by KGoodale13** [comment]
@Collision02 Are you kidding me? @7Flixs's code is much cleaner first of all. Second of all the only way to check all those ports to find the local discord RPC server is to try them all until you find the correct one. Marceau's solution was to try every single port using a for loop and continue searching even *after* the correct port was found. Flixs' solution ( which was much better ) was to try the first port which 99% of the time will be the correct port and then if and only if it fails does he continue checking the other ports. How can you possibly say Marceau's solution which was far worse was stolen?

**Comment by Tenrys** [comment]
I don't deny that the code looks cleaner and may work a little smoother with some additions on top of it. However my main concern as @DevulTj said is that it's his code that the author rewrote which ultimately was borrowed from me, and that in the end I didn't end up being credited anywhere as if they suddenly had an epiphany about how this worked around the time my library released.

I definitely don't think this warrants a DMCA however I do feel a little upset / ripped off, and there is the fact that the code is rewrote from mine and there was a change of license.

I'm just asking for credit and usage of the license I chose.

**Comment by DevulTj** [comment]
Let's not jump into coding conventions.

I don't think you understand, I didn't borrow your code. I looked at it for **some** inspiration. I never once copied anything word for word - only the concept/idea of how to get things done. I made **many improvements** along the way, and ultimately it's the reason I didn't choose to use your script in the first place. Flixs saw that my code also could see improvements, hence you see this here script.

At the end of the day, maybe a thank you should have been nice, but your licensing is in no way warranting to claim such a concept or idea to be owned by you.
 
I hope this situation can end swiftly. Thanks for reading.

**Comment by Collision02** [comment]
@DevulTj noone is claiming that "a concept or idea is owned by Tenrys".
If you look at the examples provided in the OP, @7Flixs code can be mapped line-by-line to Tenrys' code, as if he took Tenrys' code, copypasted it and then changed the style, claiming it to be his own, thus violating GPL. That's the point of this post, not some "concept theft".

**Comment by KGoodale13** [comment]
@Collision02 Your personal preference of not liking Hungarian notation is irrelevant. Both of these libraries were made with the same language for the same game to do the same exact thing. They both were made to interface with Discord RPC which has set specifications. The *only* similar things between these two libraries are things that there really isn't much flexibility with. You need to find the discord rpc port. Both projects do that and they both do it still slightly differently. The structure of the two isn't even similar. @Tenrys has some states file used to configure the states, While @7Flixs uses hooks to get activity info. Bottom line just because @Tenrys also made a Discord RPC library doesn't mean he deserves credit for all discord rpc libraries made in gmod for the rest of time. There's a reason this project exists and it's because @7Flixs needed to integrate Discord RPC into a gamemode and he did not like @Tenrys library.

**Comment by Collision02** [comment]
@KGoodale13 >Your personal preference of not liking Hungarian notation is irrelevant.
Then why did you bring subjective statements like 
> 7Flixs's code is much cleaner first of all.
into the discussion in the first place? 🤔 
> [ rest of the post ]
See https://github.com/7Flixs/glua_discord/issues/1#issuecomment-380602367

**Comment by Tenrys** [comment]
No idea what stopped anyone from taking my add-on and slapping it in their gamemode's files, but okay.

**Comment by DevulTj** [comment]
Because it's inherently slower than the version we have written?

You are both now wasting your time with this quarrel. Competition is natural and healthy. Let's move on.

**Comment by Collision02** [comment]
@DevulTj dude you have some 5 revisions infringing on copyright regardless of the HEAD commit or your personal opinion.

**Comment by DevulTj** [comment]
What?

**Comment by Collision02** [comment]
@DevulTj updated previous comment

**Comment by Collision02** [comment]
@KGoodale13 descending to personal insults is the proper way to behave.
https://pastebin.com/WM97Mi9F
gl passing a code review when (if) you get a job.

We will be seeking alternative ways of influencing this cituation.

**Comment by DevulTj** [comment]
https://i.devultj.co.uk/6mg266.png

I'm not gonna take you seriously from now.

**Comment by 7Flixs** [comment]
Hey, @Collision02 since this seemed to be your last issue I've cleard the git history so you wont have that problem in the future more, since this issue seems to be solved thanks for your time and sorry for the inconvenience!

**Comment by Collision02** [comment]
Thanks @7Flixs
