### ISSUE TITLE
Where to find certain Values

### ISSUE THREAD

**Issue by Zarken-Dev** [7Flixs/glua_discord#2]
Not really an issue - but don't know where else to contact you.

Where can i get the "CLIENT_ID", "PROCESS_ID" and "CLIENT_SECRET" Values? I'm assuming it's pretty obvious but I cant work it out.

I assume after those i just put this in some sort of lua folder? xD

I apologize is this is stupid / self explanatory. Its late maybe thats why I can't find out.

**Comment by 7Flixs** [comment]
@Zarken-Dev you have to go onto this website:
https://discordapp.com/developers/applications/me

There you will have to create an application, you can find the CLIENT_ID and CLIENT_SECRET directly on top, make sure not to share the SECRET one. If you scroll down futher more, you will find the PROCESS_ID, in the bot information field, YOUR_APPLICATION#1234 in this case 1234 would be the PROCESS_ID. And for if you scroll down even futher you can customize your discord rich presence on how it will look later.

**Comment by Zarken-Dev** [comment]
Thanks for the detailed reply. I'm assuming i dont have to host the app on a server as well? (like i do with my bot)
